//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

namespace MindMate.View.Ribbon
{
    public enum RibbonMarkupCommands : uint
    {
		ApplicationMenu = 1000,		
		ButtonNew = 1001,		
		ButtonOpen = 1002,		
		ButtonSave = 1003,		
		SaveAs = 1007,		
		SaveAll = 1006,		
		Export = 1010,		
		ExportAsPNG = 1008,		
		ExportAsJPG = 1009,		
		Close = 1005,		
		ButtonExit = 1004,		
		RecentItems = 1020,		
		TabHome = 2000,		
		NewNode = 2010,		
		NewChildNode = 2011,		
		NewLongNode = 2012,		
		NewNodeAbove = 2013,		
		NewNodeBelow = 2014,		
		NewNodeParent = 2015,		
		GrpEdit = 2030,		
		EditText = 2031,		
		EditLong = 2032,		
		DeleteNode = 2033,		
		GrpClipboard = 2050,		
		Paste = 2051,		
		PasteAsText = 2052,		
		Cut = 2053,		
		Copy = 2054,		
		FormatPainter = 2055,		
		GrpFont = 2070,		
		RichFont = 2071,		
		GrpIcons = 2080,		
		IconsGallery = 2081,		
		RemoveLastIcon = 2082,		
		RemoveAllIcons = 2083,		
		LaunchIconsDialog = 2084,		
		TabEdit = 3000,		
		GrpSelect = 3010,		
		SelectAll = 3011,		
		SelectSiblings = 3012,		
		SelectAncestors = 3013,		
		SelectChildren = 3014,		
		SelectDescendents = 3015,		
		SelectDescendentsUpto1 = 3016,		
		SelectDescendentsUpto2 = 3017,		
		SelectDescendentsUpto3 = 3018,		
		SelectDescendentsUpto4 = 3019,		
		SelectDescendentsUpto5 = 3020,		
		ExpandOnSelect = 3029,		
		SelectLevel = 3022,		
		SelectLevel1 = 3023,		
		SelectLevel2 = 3024,		
		SelectLevel3 = 3025,		
		SelectLevel4 = 3026,		
		SelectLevel5 = 3027,		
		SelectLevelCurrent = 3028,		
		GrpExpand = 3101,		
		ExpandAll = 3102,		
		CollapseAll = 3103,		
		ToggleCurrent = 3104,		
		ToggleBranch = 3105,		
		ExpandMapToCurrentLevel = 3110,		
		ExpandMapToLevel1 = 3111,		
		ExpandMapToLevel2 = 3112,		
		ExpandMapToLevel3 = 3113,		
		ExpandMapToLevel4 = 3114,		
		ExpandMapToLevel5 = 3115,		
	}
}
